name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Run tests (replace with your actual test command)
        run: docker-compose -f docker-compose.yml exec app yarn test

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down
